import Head from 'next/head'
import { Inter } from '@next/font/google'
import { DarkModeSwitch } from 'react-toggle-dark-mode';
import { useEffect, useState } from 'react';
import { useTheme } from 'next-themes'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { setTheme } = useTheme()
  const [mounted, setMounted] = useState(false)
  const [darkMode, setDarkMode] = useState(false);

  useEffect(() => {
    setMounted(true)
  }, [])

  useEffect(() => {
    const theme = darkMode ? 'dark' : 'light';
    setTheme(theme)
  }, [darkMode])

  if (!mounted) {
    return null
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='text-lg flex flex-col min-h-screen p-12 dark:bg-zinc-900 bg-zinc-50'>
        <header className='flex justify-end'>
          <button className='flex h-12 w-12 rounded-full items-center justify-center bg-zinc-900 dark:bg-zinc-50 '>
            <DarkModeSwitch
              checked={!darkMode}
              onChange={() => setDarkMode(!darkMode)}
            />
          </button>
        </header>

        <section className='py-10 border-b border-zinc-300 dark:border-[#2c2c2c]'>
          <h3 className='text-xl font-bold mb-2.5'>Technical Skills</h3>
          <ul className='pl-12'>
            <li>Programming Languages: HTML, CSS, JavaScript, TypeScript
            </li>
            <li>Frameworks and Libraries: React, Next, ReactNative, Bootstrap, JQuery, Tailwind, Socket.io,  Puppeteer, CodeMirror
            </li>
            <li>Databases: MongoDB</li>
            <li>Tools: Git, JIRA, Trello
            </li>
          </ul>
        </section>
        <section className='py-10 border-b border-zinc-300 dark:border-[#2c2c2c]'>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe molestias delectus omnis labore. Inventore iste ducimus tempore excepturi labore similique vero eius repellat, porro eos enim, perspiciatis nihil iusto fuga.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe molestias delectus omnis labore. Inventore iste ducimus tempore excepturi labore similique vero eius repellat, porro eos enim, perspiciatis nihil iusto fuga.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe molestias delectus omnis labore. Inventore iste ducimus tempore excepturi labore similique vero eius repellat, porro eos enim, perspiciatis nihil iusto fuga.</p>
        </section>
        <section className='py-10 border-b border-zinc-300 dark:border-[#2c2c2c]'>
            <h3 className='text-xl font-bold mb-2.5'>Projects</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe molestias delectus omnis labore. Inventore iste ducimus tempore excepturi labore similique vero eius repellat, porro eos enim, perspiciatis nihil iusto fuga.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe molestias delectus omnis labore. Inventore iste ducimus tempore excepturi labore similique vero eius repellat, porro eos enim, perspiciatis nihil iusto fuga.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe molestias delectus omnis labore. Inventore iste ducimus tempore excepturi labore similique vero eius repellat, porro eos enim, perspiciatis nihil iusto fuga.</p>
        </section>
        <footer>
          <div className='flex p-16 justify-around'>
            <a href="" className='hover:underline hover:underline-offset-4 hover:decoration-2	 dark:hover:text-pink-500'>GitHub</a>
            <a href="" className='hover:underline hover:underline-offset-4 hover:decoration-2	 dark:hover:text-pink-500'>LinkedIn</a>
            <a href="" className='hover:underline hover:underline-offset-4 hover:decoration-2	 dark:hover:text-pink-500'>Resume</a>
          </div>
          <div className='flex justify-center' onClick={() => {
            window.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
          }}>
            <button className='w-12 h-12 flex items-center justify-center bg-zinc-900 text-zinc-50 dark:bg-zinc-50 dark:text-zinc-900 rounded-full'>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
              </svg>
            </button>
          </div>

        </footer> 
      </main>

    </>
  )
}
